//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace CapaPersistencia
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(COMPRADEMATERIAPRIMA))]
    [KnownType(typeof(PRODUCTOTERMINADO))]
    public partial class LOTE: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Simple Properties
    
        [DataMember]
        public int IDLOTE
        {
            get { return _iDLOTE; }
            set
            {
                if (_iDLOTE != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'IDLOTE' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _iDLOTE = value;
                    OnPropertyChanged("IDLOTE");
                }
            }
        }
        private int _iDLOTE;
    
        [DataMember]
        public string NOMBRE
        {
            get { return _nOMBRE; }
            set
            {
                if (_nOMBRE != value)
                {
                    _nOMBRE = value;
                    OnPropertyChanged("NOMBRE");
                }
            }
        }
        private string _nOMBRE;
    
        [DataMember]
        public Nullable<decimal> PESO
        {
            get { return _pESO; }
            set
            {
                if (_pESO != value)
                {
                    _pESO = value;
                    OnPropertyChanged("PESO");
                }
            }
        }
        private Nullable<decimal> _pESO;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<COMPRADEMATERIAPRIMA> COMPRADEMATERIAPRIMAs
        {
            get
            {
                if (_cOMPRADEMATERIAPRIMAs == null)
                {
                    _cOMPRADEMATERIAPRIMAs = new TrackableCollection<COMPRADEMATERIAPRIMA>();
                    _cOMPRADEMATERIAPRIMAs.CollectionChanged += FixupCOMPRADEMATERIAPRIMAs;
                }
                return _cOMPRADEMATERIAPRIMAs;
            }
            set
            {
                if (!ReferenceEquals(_cOMPRADEMATERIAPRIMAs, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_cOMPRADEMATERIAPRIMAs != null)
                    {
                        _cOMPRADEMATERIAPRIMAs.CollectionChanged -= FixupCOMPRADEMATERIAPRIMAs;
                    }
                    _cOMPRADEMATERIAPRIMAs = value;
                    if (_cOMPRADEMATERIAPRIMAs != null)
                    {
                        _cOMPRADEMATERIAPRIMAs.CollectionChanged += FixupCOMPRADEMATERIAPRIMAs;
                    }
                    OnNavigationPropertyChanged("COMPRADEMATERIAPRIMAs");
                }
            }
        }
        private TrackableCollection<COMPRADEMATERIAPRIMA> _cOMPRADEMATERIAPRIMAs;
    
        [DataMember]
        public TrackableCollection<PRODUCTOTERMINADO> PRODUCTOTERMINADOes
        {
            get
            {
                if (_pRODUCTOTERMINADOes == null)
                {
                    _pRODUCTOTERMINADOes = new TrackableCollection<PRODUCTOTERMINADO>();
                    _pRODUCTOTERMINADOes.CollectionChanged += FixupPRODUCTOTERMINADOes;
                }
                return _pRODUCTOTERMINADOes;
            }
            set
            {
                if (!ReferenceEquals(_pRODUCTOTERMINADOes, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_pRODUCTOTERMINADOes != null)
                    {
                        _pRODUCTOTERMINADOes.CollectionChanged -= FixupPRODUCTOTERMINADOes;
                    }
                    _pRODUCTOTERMINADOes = value;
                    if (_pRODUCTOTERMINADOes != null)
                    {
                        _pRODUCTOTERMINADOes.CollectionChanged += FixupPRODUCTOTERMINADOes;
                    }
                    OnNavigationPropertyChanged("PRODUCTOTERMINADOes");
                }
            }
        }
        private TrackableCollection<PRODUCTOTERMINADO> _pRODUCTOTERMINADOes;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            COMPRADEMATERIAPRIMAs.Clear();
            PRODUCTOTERMINADOes.Clear();
        }

        #endregion

        #region Association Fixup
    
        private void FixupCOMPRADEMATERIAPRIMAs(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (COMPRADEMATERIAPRIMA item in e.NewItems)
                {
                    item.LOTE = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("COMPRADEMATERIAPRIMAs", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (COMPRADEMATERIAPRIMA item in e.OldItems)
                {
                    if (ReferenceEquals(item.LOTE, this))
                    {
                        item.LOTE = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("COMPRADEMATERIAPRIMAs", item);
                    }
                }
            }
        }
    
        private void FixupPRODUCTOTERMINADOes(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (PRODUCTOTERMINADO item in e.NewItems)
                {
                    item.LOTE = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("PRODUCTOTERMINADOes", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (PRODUCTOTERMINADO item in e.OldItems)
                {
                    if (ReferenceEquals(item.LOTE, this))
                    {
                        item.LOTE = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("PRODUCTOTERMINADOes", item);
                    }
                }
            }
        }

        #endregion

    }
}
