//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace CapaPersistencia
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(COMPRADEMATERIAPRIMA))]
    [KnownType(typeof(TIPOMATERIAPRIMA))]
    public partial class PROVEEDOR: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Simple Properties
    
        [DataMember]
        public int IDPROVEEDOR
        {
            get { return _iDPROVEEDOR; }
            set
            {
                if (_iDPROVEEDOR != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'IDPROVEEDOR' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _iDPROVEEDOR = value;
                    OnPropertyChanged("IDPROVEEDOR");
                }
            }
        }
        private int _iDPROVEEDOR;
    
        [DataMember]
        public int IDTIPOMATERIAPRIMA
        {
            get { return _iDTIPOMATERIAPRIMA; }
            set
            {
                if (_iDTIPOMATERIAPRIMA != value)
                {
                    ChangeTracker.RecordOriginalValue("IDTIPOMATERIAPRIMA", _iDTIPOMATERIAPRIMA);
                    if (!IsDeserializing)
                    {
                        if (TIPOMATERIAPRIMA != null && TIPOMATERIAPRIMA.IDTIPOMATERIAPRIMA != value)
                        {
                            TIPOMATERIAPRIMA = null;
                        }
                    }
                    _iDTIPOMATERIAPRIMA = value;
                    OnPropertyChanged("IDTIPOMATERIAPRIMA");
                }
            }
        }
        private int _iDTIPOMATERIAPRIMA;
    
        [DataMember]
        public string NOMBREPROVEEDOR
        {
            get { return _nOMBREPROVEEDOR; }
            set
            {
                if (_nOMBREPROVEEDOR != value)
                {
                    _nOMBREPROVEEDOR = value;
                    OnPropertyChanged("NOMBREPROVEEDOR");
                }
            }
        }
        private string _nOMBREPROVEEDOR;
    
        [DataMember]
        public string COMUNIDAD
        {
            get { return _cOMUNIDAD; }
            set
            {
                if (_cOMUNIDAD != value)
                {
                    _cOMUNIDAD = value;
                    OnPropertyChanged("COMUNIDAD");
                }
            }
        }
        private string _cOMUNIDAD;
    
        [DataMember]
        public Nullable<bool> ESTADO
        {
            get { return _eSTADO; }
            set
            {
                if (_eSTADO != value)
                {
                    _eSTADO = value;
                    OnPropertyChanged("ESTADO");
                }
            }
        }
        private Nullable<bool> _eSTADO;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<COMPRADEMATERIAPRIMA> COMPRADEMATERIAPRIMAs
        {
            get
            {
                if (_cOMPRADEMATERIAPRIMAs == null)
                {
                    _cOMPRADEMATERIAPRIMAs = new TrackableCollection<COMPRADEMATERIAPRIMA>();
                    _cOMPRADEMATERIAPRIMAs.CollectionChanged += FixupCOMPRADEMATERIAPRIMAs;
                }
                return _cOMPRADEMATERIAPRIMAs;
            }
            set
            {
                if (!ReferenceEquals(_cOMPRADEMATERIAPRIMAs, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_cOMPRADEMATERIAPRIMAs != null)
                    {
                        _cOMPRADEMATERIAPRIMAs.CollectionChanged -= FixupCOMPRADEMATERIAPRIMAs;
                    }
                    _cOMPRADEMATERIAPRIMAs = value;
                    if (_cOMPRADEMATERIAPRIMAs != null)
                    {
                        _cOMPRADEMATERIAPRIMAs.CollectionChanged += FixupCOMPRADEMATERIAPRIMAs;
                    }
                    OnNavigationPropertyChanged("COMPRADEMATERIAPRIMAs");
                }
            }
        }
        private TrackableCollection<COMPRADEMATERIAPRIMA> _cOMPRADEMATERIAPRIMAs;
    
        [DataMember]
        public TIPOMATERIAPRIMA TIPOMATERIAPRIMA
        {
            get { return _tIPOMATERIAPRIMA; }
            set
            {
                if (!ReferenceEquals(_tIPOMATERIAPRIMA, value))
                {
                    var previousValue = _tIPOMATERIAPRIMA;
                    _tIPOMATERIAPRIMA = value;
                    FixupTIPOMATERIAPRIMA(previousValue);
                    OnNavigationPropertyChanged("TIPOMATERIAPRIMA");
                }
            }
        }
        private TIPOMATERIAPRIMA _tIPOMATERIAPRIMA;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            COMPRADEMATERIAPRIMAs.Clear();
            TIPOMATERIAPRIMA = null;
        }

        #endregion

        #region Association Fixup
    
        private void FixupTIPOMATERIAPRIMA(TIPOMATERIAPRIMA previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.PROVEEDORs.Contains(this))
            {
                previousValue.PROVEEDORs.Remove(this);
            }
    
            if (TIPOMATERIAPRIMA != null)
            {
                TIPOMATERIAPRIMA.PROVEEDORs.Add(this);
    
                IDTIPOMATERIAPRIMA = TIPOMATERIAPRIMA.IDTIPOMATERIAPRIMA;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("TIPOMATERIAPRIMA")
                    && (ChangeTracker.OriginalValues["TIPOMATERIAPRIMA"] == TIPOMATERIAPRIMA))
                {
                    ChangeTracker.OriginalValues.Remove("TIPOMATERIAPRIMA");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("TIPOMATERIAPRIMA", previousValue);
                }
                if (TIPOMATERIAPRIMA != null && !TIPOMATERIAPRIMA.ChangeTracker.ChangeTrackingEnabled)
                {
                    TIPOMATERIAPRIMA.StartTracking();
                }
            }
        }
    
        private void FixupCOMPRADEMATERIAPRIMAs(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (COMPRADEMATERIAPRIMA item in e.NewItems)
                {
                    item.PROVEEDOR = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("COMPRADEMATERIAPRIMAs", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (COMPRADEMATERIAPRIMA item in e.OldItems)
                {
                    if (ReferenceEquals(item.PROVEEDOR, this))
                    {
                        item.PROVEEDOR = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("COMPRADEMATERIAPRIMAs", item);
                    }
                }
            }
        }

        #endregion

    }
}
