//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace CapaPersistencia
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(COMPRADEMATERIAPRIMA))]
    [KnownType(typeof(PROVEEDOR))]
    public partial class TIPOMATERIAPRIMA: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Simple Properties
    
        [DataMember]
        public int IDTIPOMATERIAPRIMA
        {
            get { return _iDTIPOMATERIAPRIMA; }
            set
            {
                if (_iDTIPOMATERIAPRIMA != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'IDTIPOMATERIAPRIMA' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _iDTIPOMATERIAPRIMA = value;
                    OnPropertyChanged("IDTIPOMATERIAPRIMA");
                }
            }
        }
        private int _iDTIPOMATERIAPRIMA;
    
        [DataMember]
        public string NOMBRETIPOMATERIAPRIMA
        {
            get { return _nOMBRETIPOMATERIAPRIMA; }
            set
            {
                if (_nOMBRETIPOMATERIAPRIMA != value)
                {
                    _nOMBRETIPOMATERIAPRIMA = value;
                    OnPropertyChanged("NOMBRETIPOMATERIAPRIMA");
                }
            }
        }
        private string _nOMBRETIPOMATERIAPRIMA;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<COMPRADEMATERIAPRIMA> COMPRADEMATERIAPRIMAs
        {
            get
            {
                if (_cOMPRADEMATERIAPRIMAs == null)
                {
                    _cOMPRADEMATERIAPRIMAs = new TrackableCollection<COMPRADEMATERIAPRIMA>();
                    _cOMPRADEMATERIAPRIMAs.CollectionChanged += FixupCOMPRADEMATERIAPRIMAs;
                }
                return _cOMPRADEMATERIAPRIMAs;
            }
            set
            {
                if (!ReferenceEquals(_cOMPRADEMATERIAPRIMAs, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_cOMPRADEMATERIAPRIMAs != null)
                    {
                        _cOMPRADEMATERIAPRIMAs.CollectionChanged -= FixupCOMPRADEMATERIAPRIMAs;
                    }
                    _cOMPRADEMATERIAPRIMAs = value;
                    if (_cOMPRADEMATERIAPRIMAs != null)
                    {
                        _cOMPRADEMATERIAPRIMAs.CollectionChanged += FixupCOMPRADEMATERIAPRIMAs;
                    }
                    OnNavigationPropertyChanged("COMPRADEMATERIAPRIMAs");
                }
            }
        }
        private TrackableCollection<COMPRADEMATERIAPRIMA> _cOMPRADEMATERIAPRIMAs;
    
        [DataMember]
        public TrackableCollection<PROVEEDOR> PROVEEDORs
        {
            get
            {
                if (_pROVEEDORs == null)
                {
                    _pROVEEDORs = new TrackableCollection<PROVEEDOR>();
                    _pROVEEDORs.CollectionChanged += FixupPROVEEDORs;
                }
                return _pROVEEDORs;
            }
            set
            {
                if (!ReferenceEquals(_pROVEEDORs, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_pROVEEDORs != null)
                    {
                        _pROVEEDORs.CollectionChanged -= FixupPROVEEDORs;
                    }
                    _pROVEEDORs = value;
                    if (_pROVEEDORs != null)
                    {
                        _pROVEEDORs.CollectionChanged += FixupPROVEEDORs;
                    }
                    OnNavigationPropertyChanged("PROVEEDORs");
                }
            }
        }
        private TrackableCollection<PROVEEDOR> _pROVEEDORs;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            COMPRADEMATERIAPRIMAs.Clear();
            PROVEEDORs.Clear();
        }

        #endregion

        #region Association Fixup
    
        private void FixupCOMPRADEMATERIAPRIMAs(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (COMPRADEMATERIAPRIMA item in e.NewItems)
                {
                    item.TIPOMATERIAPRIMA = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("COMPRADEMATERIAPRIMAs", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (COMPRADEMATERIAPRIMA item in e.OldItems)
                {
                    if (ReferenceEquals(item.TIPOMATERIAPRIMA, this))
                    {
                        item.TIPOMATERIAPRIMA = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("COMPRADEMATERIAPRIMAs", item);
                    }
                }
            }
        }
    
        private void FixupPROVEEDORs(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (PROVEEDOR item in e.NewItems)
                {
                    item.TIPOMATERIAPRIMA = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("PROVEEDORs", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (PROVEEDOR item in e.OldItems)
                {
                    if (ReferenceEquals(item.TIPOMATERIAPRIMA, this))
                    {
                        item.TIPOMATERIAPRIMA = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("PROVEEDORs", item);
                    }
                }
            }
        }

        #endregion

    }
}
