//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace CapaPersistencia
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(PRODUCTOTERMINADO))]
    public partial class TIPOPRODUCTOTERMINADO: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Simple Properties
    
        [DataMember]
        public int IDTIPOPRODUCTOTERMINADO
        {
            get { return _iDTIPOPRODUCTOTERMINADO; }
            set
            {
                if (_iDTIPOPRODUCTOTERMINADO != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'IDTIPOPRODUCTOTERMINADO' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _iDTIPOPRODUCTOTERMINADO = value;
                    OnPropertyChanged("IDTIPOPRODUCTOTERMINADO");
                }
            }
        }
        private int _iDTIPOPRODUCTOTERMINADO;
    
        [DataMember]
        public string NOMREPRODUCTOTERMINADO
        {
            get { return _nOMREPRODUCTOTERMINADO; }
            set
            {
                if (_nOMREPRODUCTOTERMINADO != value)
                {
                    _nOMREPRODUCTOTERMINADO = value;
                    OnPropertyChanged("NOMREPRODUCTOTERMINADO");
                }
            }
        }
        private string _nOMREPRODUCTOTERMINADO;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<PRODUCTOTERMINADO> PRODUCTOTERMINADOes
        {
            get
            {
                if (_pRODUCTOTERMINADOes == null)
                {
                    _pRODUCTOTERMINADOes = new TrackableCollection<PRODUCTOTERMINADO>();
                    _pRODUCTOTERMINADOes.CollectionChanged += FixupPRODUCTOTERMINADOes;
                }
                return _pRODUCTOTERMINADOes;
            }
            set
            {
                if (!ReferenceEquals(_pRODUCTOTERMINADOes, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_pRODUCTOTERMINADOes != null)
                    {
                        _pRODUCTOTERMINADOes.CollectionChanged -= FixupPRODUCTOTERMINADOes;
                    }
                    _pRODUCTOTERMINADOes = value;
                    if (_pRODUCTOTERMINADOes != null)
                    {
                        _pRODUCTOTERMINADOes.CollectionChanged += FixupPRODUCTOTERMINADOes;
                    }
                    OnNavigationPropertyChanged("PRODUCTOTERMINADOes");
                }
            }
        }
        private TrackableCollection<PRODUCTOTERMINADO> _pRODUCTOTERMINADOes;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            PRODUCTOTERMINADOes.Clear();
        }

        #endregion

        #region Association Fixup
    
        private void FixupPRODUCTOTERMINADOes(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (PRODUCTOTERMINADO item in e.NewItems)
                {
                    item.TIPOPRODUCTOTERMINADO = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("PRODUCTOTERMINADOes", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (PRODUCTOTERMINADO item in e.OldItems)
                {
                    if (ReferenceEquals(item.TIPOPRODUCTOTERMINADO, this))
                    {
                        item.TIPOPRODUCTOTERMINADO = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("PRODUCTOTERMINADOes", item);
                    }
                }
            }
        }

        #endregion

    }
}
